[build]
  base    = "client"
  publish = "/build"

  [[redirects]]
  from = "https://5fbbfd58f165b100088c49ff--optimistic-bell-e4dd1f.netlify.app/helloWorld"
  to = "https://us-central1-stock-fantasy-fd46e.cloudfunctions.net/helloWorld"