[build]
  base    = "client"
  publish = "/build"

  [[redirects]]
  from = "/helloWorld"
  to = "https://us-central1-stock-fantasy-fd46e.cloudfunctions.net/helloWorld"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
